package:
  name: lintools
  version: 0.3
build:
  number: 0


source:
  git_rev: v0.3
  git_url: https://github.com/ldomic/lintools.git

requirements:
  build:
    - python
    - setuptools
    - python
    - rdkit/rdkit
    - matplotlib
    - geos
    - shapely
    - numpy
    - MDAnalysis/mdanalysis
    - omnia/mdtraj

  run:
    - python
    - rdkit
    - matplotlib
    - geos
    - shapely
    - numpy
    - mdanalysis
    - mdtraj
    - pyyaml

test:
  imports:
    - lintools.lintools

about:
  home: https://github.com/ldomic/lintools
  license: GPL
  license_file: LICENCE.md
