package:
  name: lintools
  version: 0.3
build:
  number: 0
  entry_points:
    - lintools:lintools.__main__:main  

source:
  git_rev: v0.3
  git_url: https://github.com/ldomic/lintools.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rdkit 2016.03.4
    - matplotlib
    - geos
    - shapely
    - numpy
    - mdanalysis 0.16.0
    - mdtraj 1.7.2
    - pyyaml

test:
  imports:
    - lintools.lintools
  source_files:
    - lintools/testdata
  requires:
    - nose
  test:
    - testdata/test_topol.py    
about:
  home: https://github.com/ldomic/lintools
  license: GPL
  license_file: LICENCE.md
