os:
  - osx
env:
  global:
    - GH_DOC_BRANCH: master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $(pwd)/miniconda
  - export PATH=$(pwd)/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -c https://conda.anaconda.org/rdkit -n my-rdkit-env rdkit==2016.03.4 python=2.7
  - source activate my-rdkit-env
  - conda install -y -n my-rdkit-env python=2.7 numpy  cython nose matplotlib geos shapely scipy 
  - travis_wait conda install -c omnia openbabel=2015.09
  - pip install MDAnalysis==0.16.0  coveralls mdtraj
  - wget http://pyyaml.org/download/pyyaml/PyYAML-3.12.tar.gz
  - tar -zxvf PyYAML-3.12.tar.gz
  - cd PyYAML-3.12
  - python setup.py install
  - cd ../
  - python setup.py build
  - python setup.py install
script:
  - nosetests --with-coverage --cover-package lintools lintools/testdata/test_topol.py
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}"
after_success:
  - coveralls
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}"
