package:
  name:lintools
  version:”0.2”
build:
  string:py27


source:
  git_rev:v0.2
  git_url:https://github.com/ldomic/lintools.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rdkit
    - matplotlib
    - geos
    - shapely
    - numpy
    - mdanalysis

test:
  source_files:
    - lintools/testdata
  requires:
    - nose
  test:
    - testdata/test_topol.py


about:
  home:https://github.com/ldomic/lintools
  license:GPL-3.0
  license_file:LICENCE.md
  summary:Produces 2D protein-ligand interaction plots.