# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /lintools/recipes, last modified Fri Jun  2 16:03:38 2017
# ------------------------------------------------

package:
    name: lintools
    version: '0.3'
source:
    git_rev: v0.3
    git_url: /lintools/recipes/https:/github.com/ldomic/lintools.git
build:
    noarch: ''
    noarch_python: false
    script: python setup.py install
    string: py27_0
requirements:
    build:
        - mdanalysis 0.15.0 py27_1
        - zlib 1.2.8 3
        - cairo 1.14.8 0
        - setuptools 27.2.0 py27_0
        - gst-plugins-base 1.8.0 0
        - numpy 1.11.3 py27_0
        - decorator 4.0.11 py27_0
        - libxcb 1.12 1
        - biopython 1.68 np111py27_0
        - fontconfig 2.12.1 3
        - functools32 3.2.3.2 py27_0
        - gstreamer 1.8.0 0
        - libiconv 1.14 0
        - python 2.7.13 0
        - dbus 1.10.10 0
        - scipy 0.19.0 np111py27_0
        - sip 4.18 py27_0
        - pytz 2017.2 py27_0
        - jpeg 9b 0
        - wheel 0.29.0 py27_0
        - matplotlib 2.0.2 np111py27_0
        - six 1.10.0 py27_0
        - tempdir 0.7.1 py27_1
        - openssl 1.0.2l 0
        - libnetcdf 4.4.1 0
        - tk 8.5.18 0
        - curl 7.49.0 1
        - libpng 1.6.27 0
        - pyparsing 2.1.4 py27_0
        - qt 5.6.2 4
        - hdf4 4.2.12 1
        - libxml2 2.9.4 0
        - readline 6.2 2
        - glib 2.50.2 1
        - cycler 0.10.0 py27_0
        - mkl 2017.0.1 0
        - python-dateutil 2.6.0 py27_0
        - pycairo 1.10.0 py27_0
        - seaborn 0.7.1 py27_0
        - icu 54.1 0
        - netcdf4 1.2.4 np111py27_0
        - nose 1.3.7 py27_1
        - libgfortran 3.0.0 1
        - freetype 2.5.5 2
        - pip 9.0.1 py27_1
        - libffi 3.2.1 1
        - pyqt 5.6.0 py27_2
        - sqlite 3.13.0 0
        - pixman 0.34.0 0
        - expat 2.1.0 0
        - libgcc 5.2.0 0
        - hdf5 1.8.17 1
        - pcre 8.39 1
        - networkx 1.11 py27_0
        - pandas 0.20.1 np111py27_0
        - griddataformats 0.3.3 py_0
        - subprocess32 3.2.7 py27_0
    run:
        - python
        - rdkit
        - matplotlib
        - geos
        - shapely
        - numpy
        - mdanalysis
        - mdtraj
test:
    requires:
        - nose
    source_files:
        - lintools/testdata
    test:
        - testdata/test_topol.py
about:
    home: https://github.com/ldomic/lintools
    license: GPL
    license_file: LICENCE.md
extra:
    final: true
