# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /lintools/recipes, last modified Fri Jun  2 15:42:28 2017
# ------------------------------------------------

package:
    name: lintools
    version: '0.3'
source:
    git_rev: v0.3
    git_url: /lintools/recipes/https:/github.com/ldomic/lintools.git
build:
    noarch: ''
    noarch_python: false
    script: python setup.py install
    string: py27_0
requirements:
    build:
        - zlib 1.2.8 3
        - pip 9.0.1 py27_1
        - setuptools 27.2.0 py27_0
        - readline 6.2 2
        - wheel 0.29.0 py27_0
        - openssl 1.0.2l 0
        - tk 8.5.18 0
        - sqlite 3.13.0 0
        - python 2.7.13 0
    run:
        - python
        - rdkit
        - matplotlib
        - geos
        - shapely
        - numpy
        - mdanalysis
        - mdtraj
test:
    requires:
        - nose
    source_files:
        - lintools/testdata
    test:
        - testdata/test_topol.py
about:
    home: https://github.com/ldomic/lintools
    license: GPL
    license_file: LICENCE.md
extra:
    final: true
